server:
  port: 8000

spring:
  application:
    name: auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      client-id: myclient
      client-secret: myclientsecret